setwd('C:/Users/Khuram Afzal/Desktop/EC CENSUS')
json_raw <- readLines('dashboard_data.json', warn=FALSE, encoding='UTF-8')
json_str  <- paste(json_raw, collapse='\n')

lines <- c(
'<!DOCTYPE html>',
'<html lang="en">',
'<head>',
'<meta charset="UTF-8">',
'<meta name="viewport" content="width=device-width, initial-scale=1.0">',
'<title>EC Census Punjab Dashboard</title>',
'<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>',
'<style>',
'*{box-sizing:border-box;margin:0;padding:0}',
'body{font-family:"Segoe UI",Arial,sans-serif;background:#f0f4f8;color:#1a2636;min-height:100vh}',
'.header{background:linear-gradient(135deg,#1a3a5c 0%,#0e6e4e 100%);color:#fff;padding:22px 32px;display:flex;align-items:center;gap:18px}',
'.header-logo{font-size:40px}',
'.header-text h1{font-size:20px;font-weight:700;letter-spacing:.4px}',
'.header-text p{font-size:12px;opacity:.85;margin-top:3px}',
'.filters{background:#fff;padding:18px 32px;display:flex;flex-wrap:wrap;gap:16px;align-items:flex-end;box-shadow:0 2px 8px rgba(0,0,0,.08)}',
'.filter-group{display:flex;flex-direction:column;gap:5px;min-width:190px}',
'.filter-group label{font-size:11px;font-weight:700;color:#1a3a5c;text-transform:uppercase;letter-spacing:.5px}',
'.filter-group select{padding:9px 36px 9px 12px;border:1.5px solid #c5d5e8;border-radius:8px;font-size:13px;background:#fff;color:#1a2636;cursor:pointer;outline:none;appearance:none;background-image:url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'12\' height=\'12\' viewBox=\'0 0 12 12\'%3E%3Cpath fill=\'%231a3a5c\' d=\'M6 8L1 3h10z\'/%3E%3C/svg%3E");background-repeat:no-repeat;background-position:right 10px center}',
'.filter-group select:focus{border-color:#0e6e4e;box-shadow:0 0 0 3px rgba(14,110,78,.12)}',
'.btn-reset{padding:9px 20px;background:#1a3a5c;color:#fff;border:none;border-radius:8px;font-size:13px;font-weight:600;cursor:pointer;transition:background .2s;align-self:flex-end}',
'.btn-reset:hover{background:#0e6e4e}',
'.content{padding:22px 32px;display:flex;flex-direction:column;gap:22px}',
'.summary-row{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:14px}',
'.card{background:#fff;border-radius:12px;padding:18px 20px;box-shadow:0 2px 8px rgba(0,0,0,.07);border-left:4px solid #1a3a5c}',
'.card.green{border-left-color:#0e9e6b}.card.amber{border-left-color:#e07b00}.card.red{border-left-color:#b81a1a}.card.purple{border-left-color:#6b3fa0}',
'.card-label{font-size:11px;font-weight:600;color:#6b82a0;text-transform:uppercase;letter-spacing:.4px;margin-bottom:6px}',
'.card-value{font-size:26px;font-weight:800;color:#1a3a5c;line-height:1}',
'.card.green .card-value{color:#0e6e4e}.card.amber .card-value{color:#b8650a}.card.red .card-value{color:#b81a1a}.card.purple .card-value{color:#6b3fa0}',
'.card-sub{font-size:11px;color:#9aacbe;margin-top:4px}',
'.tabs{display:flex;gap:3px;flex-wrap:wrap}',
'.tab{padding:9px 18px;font-size:12px;font-weight:600;color:#6b82a0;cursor:pointer;border-radius:8px 8px 0 0;border:2px solid transparent;border-bottom:none;margin-bottom:-2px;transition:all .2s}',
'.tab.active{color:#1a3a5c;background:#fff;border-color:#c5d5e8;border-bottom-color:#fff}',
'.tab:hover:not(.active){color:#1a3a5c;background:#e8f0fa}',
'.tab-pane{display:none;background:#fff;border-radius:0 12px 12px 12px;box-shadow:0 2px 8px rgba(0,0,0,.07);padding:24px;border:2px solid #c5d5e8}',
'.tab-pane.active{display:block}',
'.pane-title{font-size:15px;font-weight:700;color:#1a3a5c;margin-bottom:3px}',
'.pane-sub{font-size:11px;color:#9aacbe;margin-bottom:18px}',
'.grid2{display:grid;grid-template-columns:1fr 1fr;gap:18px}',
'@media(max-width:760px){.grid2{grid-template-columns:1fr}}',
'.chart-box{background:#f8fafc;border-radius:10px;padding:16px}',
'.chart-box h4{font-size:13px;font-weight:600;color:#1a3a5c;margin-bottom:12px}',
'.chart-wrap{position:relative;height:360px}',
'.chart-wrap-tall{position:relative;height:430px}',
'.no-data{display:flex;flex-direction:column;align-items:center;justify-content:center;height:260px;color:#aaa;gap:10px}',
'.no-data span{font-size:40px}.no-data p{font-size:14px}',
'.district-badge{display:inline-flex;align-items:center;gap:6px;background:#e8f0fa;color:#1a3a5c;border-radius:20px;padding:4px 14px;font-size:12px;font-weight:700;margin-bottom:14px}',
'</style>',
'</head>',
'<body>',
'<div class="header">',
'  <div class="header-logo">&#127981;</div>',
'  <div class="header-text">',
'    <h1>Punjab Economic Census &mdash; Establishments Dashboard</h1>',
'    <p>District-level data: PSIC sectors, unit types, employment size &amp; workforce across Punjab</p>',
'  </div>',
'</div>',
'<div class="filters">',
'  <div class="filter-group"><label>Division</label>',
'    <select id="sel-div" onchange="onDivChange()"><option value="">All Divisions</option></select></div>',
'  <div class="filter-group"><label>District</label>',
'    <select id="sel-dist" onchange="onDistChange()"><option value="">Select District</option></select></div>',
'  <div class="filter-group"><label>Tehsil</label>',
'    <select id="sel-tehsil"><option value="">All Tehsils</option></select></div>',
'  <button class="btn-reset" onclick="resetAll()">&#x21ba; Reset</button>',
'</div>',
'<div class="content">',
'  <div id="summary"></div>',
'  <div>',
'    <div class="tabs">',
'      <div class="tab active" onclick="showTab(0)">&#128200; PSIC Sectors</div>',
'      <div class="tab" onclick="showTab(1)">&#127970; Unit Types</div>',
'      <div class="tab" onclick="showTab(2)">&#128101; Employment Size</div>',
'      <div class="tab" onclick="showTab(3)">&#9989; Unit &times; Employment</div>',
'    </div>',
'    <div class="tab-pane active" id="pane0">',
'      <div class="pane-title">PSIC Sector-wise Establishments &amp; Workforce</div>',
'      <div class="pane-sub">Table 1 &mdash; Establishments and workforce by major economic sector (PSIC classification). Select a district to view data.</div>',
'      <div class="grid2">',
'        <div class="chart-box"><h4>Establishments by Sector</h4><div class="chart-wrap"><canvas id="c-pe"></canvas></div></div>',
'        <div class="chart-box"><h4>Workforce by Sector</h4><div class="chart-wrap"><canvas id="c-pw"></canvas></div></div>',
'      </div>',
'    </div>',
'    <div class="tab-pane" id="pane1">',
'      <div class="pane-title">Unit Type-wise Establishments &amp; Workforce</div>',
'      <div class="pane-sub">Table 2 &mdash; Establishments and workforce by business unit type.</div>',
'      <div class="grid2">',
'        <div class="chart-box"><h4>Establishments by Unit Type</h4><div class="chart-wrap"><canvas id="c-ue"></canvas></div></div>',
'        <div class="chart-box"><h4>Workforce by Unit Type</h4><div class="chart-wrap"><canvas id="c-uw"></canvas></div></div>',
'      </div>',
'    </div>',
'    <div class="tab-pane" id="pane2">',
'      <div class="pane-title">Employment Category by PSIC Sector</div>',
'      <div class="pane-sub">Table 3 &mdash; Establishments by sector and employment size (&lt;10 vs 10+ employees).</div>',
'      <div class="chart-box"><div class="chart-wrap-tall"><canvas id="c-ec"></canvas></div></div>',
'    </div>',
'    <div class="tab-pane" id="pane3">',
'      <div class="pane-title">Unit Type by Employment Category</div>',
'      <div class="pane-sub">Table 4 &mdash; Establishments by unit type and employment size (&lt;10 vs 10+ employees).</div>',
'      <div class="chart-box"><div class="chart-wrap-tall"><canvas id="c-ute"></canvas></div></div>',
'    </div>',
'  </div>',
'</div>',
'<script>',
paste0('const D=', json_str, ';'),
'const C=["#1a6eb5","#0e9e6b","#e07b00","#b81a1a","#6b3fa0","#0e7eb5","#9e1a6b","#3fa06b","#e0a500","#1a3a5c","#5dade2","#52be80","#f39c12","#e74c3c","#9b59b6","#1abc9c","#e67e22","#3498db","#2ecc71","#e91e63"];',
'let CH={};',
'function fmt(n){return(n===null||n===undefined)?"N/A":Number(n).toLocaleString();}',
'function fk(n){if(!n)return"0";if(n>=1e6)return(n/1e6).toFixed(1)+"M";if(n>=1e3)return(n/1e3).toFixed(1)+"K";return n;}',
'function ttl(s){return s.split(" ").map(w=>w.charAt(0).toUpperCase()+w.slice(1).toLowerCase()).join(" ");}',
'const SL={',
'"Agriculture, forestry and fishing":"Agriculture",',
'"Mining and quarrying":"Mining",',
'"Manufacturing":"Manufacturing",',
'"Electricity, gas, steam and air conditioning supply":"Electricity/Gas",',
'"Water supply; sewerage, waste management and remediation activities":"Water/Waste",',
'"Construction":"Construction",',
'"Wholesale and retail trade; repair of motor vehicles and motorcycles":"Wholesale/Retail",',
'"Transportation and storage":"Transport",',
'"Accommodation and food service activities":"Food Service",',
'"Information and communication":"ICT",',
'"Financial and insurance activities":"Finance",',
'"Real estate activities":"Real Estate",',
'"Professional, scientific and technical activities":"Professional",',
'"Administrative and support service activities":"Admin Support",',
'"Public administration and defence; compulsory social security":"Public Admin",',
'"Education":"Education",',
'"Human health and social work activities":"Health",',
'"Arts, entertainment and recreation":"Arts/Rec",',
'"Other service activities":"Other Services",',
'"Activities of extraterritorial organizations and bodies":"Extraterritorial",',
'"Others":"Others"};',
'function sl(s){return SL[s]||(s.length>20?s.substr(0,18)+"...":s);}',
'// init dropdowns',
'const sdiv=document.getElementById("sel-div");',
'const sdist=document.getElementById("sel-dist");',
'const steh=document.getElementById("sel-tehsil");',
'Object.keys(D.divisions).forEach(d=>{const o=document.createElement("option");o.value=d;o.textContent=d;sdiv.appendChild(o);});',
'function onDivChange(){',
'  const div=sdiv.value;',
'  sdist.innerHTML="<option value=\\"\\">Select District</option>";',
'  const dists=div?D.divisions[div]:Object.keys(D.psic).sort();',
'  dists.forEach(d=>{const o=document.createElement("option");o.value=d;o.textContent=ttl(d);sdist.appendChild(o);});',
'  steh.innerHTML="<option value=\\"\\">All Tehsils</option>";',
'  render();',
'}',
'function onDistChange(){',
'  const dist=sdist.value;',
'  steh.innerHTML="<option value=\\"\\">All Tehsils</option>";',
'  if(dist&&D.tehsils[dist]){D.tehsils[dist].forEach(t=>{const o=document.createElement("option");o.value=t;o.textContent=t;steh.appendChild(o);});}',
'  render();',
'}',
'function resetAll(){sdiv.value="";onDivChange();}',
'function showTab(i){',
'  document.querySelectorAll(".tab").forEach((t,j)=>t.classList.toggle("active",i===j));',
'  document.querySelectorAll(".tab-pane").forEach((t,j)=>t.classList.toggle("active",i===j));',
'}',
'function dc(id){if(CH[id]){CH[id].destroy();delete CH[id];}}',
'function mkBar(id,labels,datasets,tall){',
'  dc(id);',
'  const el=document.getElementById(id);if(!el)return;',
'  CH[id]=new Chart(el,{type:"bar",data:{labels,datasets},options:{',
'    responsive:true,maintainAspectRatio:false,',
'    plugins:{legend:{position:"top",labels:{boxWidth:10,font:{size:10}}},',
'      tooltip:{callbacks:{label:c=>" "+c.dataset.label+": "+fmt(c.parsed.y)}}},',
'    scales:{',
'      x:{ticks:{font:{size:9},maxRotation:45,minRotation:20},grid:{display:false}},',
'      y:{ticks:{font:{size:9},callback:v=>fk(v)},beginAtZero:true,grid:{color:"#f0f4f8"}}',
'    }}});',
'}',
'function noData(id){dc(id);const el=document.getElementById(id);if(!el)return;const p=el.parentElement;p.innerHTML=\'<div class="no-data"><span>&#128270;</span><p>Select a district to view data</p></div>\';}',
'function rows(tbl,dist){',
'  if(!dist)return[];',
'  const r=D[tbl][dist];',
'  if(!r)return[];',
'  return Array.isArray(r)?r:Object.values(r).filter(x=>x.description!="Total");',
'}',
'function render(){',
'  const dist=sdist.value||null;',
'  // summary',
'  const pr=rows("psic",dist);',
'  const er=rows("employment",dist);',
'  const ur=rows("unit_type",dist);',
'  let te=0,tw=0,tl=0,tg=0;',
'  pr.forEach(r=>{te+=(r.establishments||0);tw+=(r.workforce||0);});',
'  er.forEach(r=>{tl+=(r.less_than_10||0);tg+=(r.ten_and_above||0);});',
'  const badge=dist?`<div class="district-badge">&#128205; ${ttl(dist)}</div>`:"";',
'  document.getElementById("summary").innerHTML=badge+`',
'  <div class="summary-row">',
'    <div class="card"><div class="card-label">Total Establishments</div><div class="card-value">${fmt(te)}</div><div class="card-sub">All sectors</div></div>',
'    <div class="card green"><div class="card-label">Total Workforce</div><div class="card-value">${fmt(tw)}</div><div class="card-sub">Persons employed</div></div>',
'    <div class="card amber"><div class="card-label">Small (< 10 empl.)</div><div class="card-value">${fmt(tl)}</div><div class="card-sub">Micro establishments</div></div>',
'    <div class="card red"><div class="card-label">Large (10+ empl.)</div><div class="card-value">${fmt(tg)}</div><div class="card-sub">Larger establishments</div></div>',
'    <div class="card purple"><div class="card-label">Active Sectors</div><div class="card-value">${pr.filter(r=>r.establishments>0).length}</div><div class="card-sub">PSIC categories</div></div>',
'    <div class="card"><div class="card-label">Unit Types</div><div class="card-value">${ur.length}</div><div class="card-sub">Distinct categories</div></div>',
'  </div>`;',
'  if(!dist){["c-pe","c-pw","c-ue","c-uw","c-ec","c-ute"].forEach(noData);return;}',
'  // PSIC charts',
'  const pf=pr.filter(r=>(r.establishments||0)+(r.workforce||0)>0);',
'  const pl=pf.map(r=>sl(r.description));',
'  mkBar("c-pe",pl,[{label:"Establishments",data:pf.map(r=>r.establishments||0),backgroundColor:pf.map((_,i)=>C[i%C.length]),borderRadius:4}]);',
'  mkBar("c-pw",pl,[{label:"Workforce",data:pf.map(r=>r.workforce||0),backgroundColor:pf.map((_,i)=>C[i%C.length]+"bb"),borderRadius:4}]);',
'  // Unit type',
'  const uf=ur.filter(r=>(r.establishments||0)>0);',
'  const ul=uf.map(r=>r.description);',
'  mkBar("c-ue",ul,[{label:"Establishments",data:uf.map(r=>r.establishments||0),backgroundColor:uf.map((_,i)=>C[i%C.length]),borderRadius:4}]);',
'  mkBar("c-uw",ul,[{label:"Workforce",data:uf.map(r=>r.workforce||0),backgroundColor:uf.map((_,i)=>C[i%C.length]+"bb"),borderRadius:4}]);',
'  // Employment category',
'  const ef=er.filter(r=>(r.less_than_10||0)+(r.ten_and_above||0)>0);',
'  const el2=ef.map(r=>sl(r.description));',
'  mkBar("c-ec",el2,[',
'    {label:"< 10 Employees",data:ef.map(r=>r.less_than_10||0),backgroundColor:"#1a6eb5",borderRadius:4},',
'    {label:"10+ Employees",data:ef.map(r=>r.ten_and_above||0),backgroundColor:"#0e9e6b",borderRadius:4}',
'  ]);',
'  // Unit type x employment',
'  const uer=rows("unit_employment",dist);',
'  const uef=uer.filter(r=>(r.less_than_10||0)+(r.ten_and_above||0)>0);',
'  const uel=uef.map(r=>r.description);',
'  mkBar("c-ute",uel,[',
'    {label:"< 10 Employees",data:uef.map(r=>r.less_than_10||0),backgroundColor:"#1a6eb5",borderRadius:4},',
'    {label:"10+ Employees",data:uef.map(r=>r.ten_and_above||0),backgroundColor:"#0e9e6b",borderRadius:4}',
'  ]);',
'}',
'onDivChange();',
'render();',
'steh.addEventListener("change",render);',
'</script>',
'</body>',
'</html>'
)

writeLines(lines, 'EC_Census_Dashboard.html', useBytes=TRUE)
cat('Done! Dashboard written to EC_Census_Dashboard.html\n')
