setwd('C:/Users/Khuram Afzal/Desktop/EC CENSUS')
json_raw <- readLines('dashboard_data.json', warn=FALSE, encoding='UTF-8')
json_str  <- paste(json_raw, collapse='\n')

lines <- c(
'<!DOCTYPE html>',
'<html lang="en">',
'<head>',
'<meta charset="UTF-8">',
'<meta name="viewport" content="width=device-width, initial-scale=1.0">',
'<title>EC Census Punjab Dashboard</title>',
'<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>',
'<style>',
'*{box-sizing:border-box;margin:0;padding:0}',
'body{font-family:"Segoe UI",Arial,sans-serif;background:#f0f4f8;color:#1a2636;min-height:100vh}',
'.header{background:linear-gradient(135deg,#1a3a5c 0%,#0e6e4e 100%);color:#fff;padding:22px 32px;display:flex;align-items:center;gap:18px}',
'.header-logo{font-size:40px}',
'.header-text h1{font-size:20px;font-weight:700;letter-spacing:.4px}',
'.header-text p{font-size:12px;opacity:.85;margin-top:3px}',
'.filters{background:#fff;padding:18px 32px;display:flex;flex-wrap:wrap;gap:16px;align-items:flex-end;box-shadow:0 2px 8px rgba(0,0,0,.08)}',
'.filter-group{display:flex;flex-direction:column;gap:5px;min-width:200px}',
'.filter-group label{font-size:11px;font-weight:700;color:#1a3a5c;text-transform:uppercase;letter-spacing:.5px}',
'.filter-group select{padding:9px 36px 9px 12px;border:1.5px solid #c5d5e8;border-radius:8px;font-size:13px;background:#fff;color:#1a2636;cursor:pointer;outline:none;appearance:none;background-image:url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'12\' height=\'12\' viewBox=\'0 0 12 12\'%3E%3Cpath fill=\'%231a3a5c\' d=\'M6 8L1 3h10z\'/%3E%3C/svg%3E");background-repeat:no-repeat;background-position:right 10px center}',
'.filter-group select:focus{border-color:#0e6e4e;box-shadow:0 0 0 3px rgba(14,110,78,.12)}',
'.btn-reset{padding:9px 20px;background:#1a3a5c;color:#fff;border:none;border-radius:8px;font-size:13px;font-weight:600;cursor:pointer;transition:background .2s;align-self:flex-end}',
'.btn-reset:hover{background:#0e6e4e}',
'.content{padding:22px 32px;display:flex;flex-direction:column;gap:22px}',
'.summary-row{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:14px}',
'.card{background:#fff;border-radius:12px;padding:18px 20px;box-shadow:0 2px 8px rgba(0,0,0,.07);border-left:4px solid #1a3a5c}',
'.card.green{border-left-color:#0e9e6b}.card.amber{border-left-color:#e07b00}.card.red{border-left-color:#b81a1a}.card.purple{border-left-color:#6b3fa0}',
'.card-label{font-size:11px;font-weight:600;color:#6b82a0;text-transform:uppercase;letter-spacing:.4px;margin-bottom:6px}',
'.card-value{font-size:26px;font-weight:800;color:#1a3a5c;line-height:1}',
'.card.green .card-value{color:#0e6e4e}.card.amber .card-value{color:#b8650a}.card.red .card-value{color:#b81a1a}.card.purple .card-value{color:#6b3fa0}',
'.card-sub{font-size:11px;color:#9aacbe;margin-top:4px}',
'.tabs{display:flex;gap:3px;flex-wrap:wrap}',
'.tab{padding:9px 18px;font-size:12px;font-weight:600;color:#6b82a0;cursor:pointer;border-radius:8px 8px 0 0;border:2px solid transparent;border-bottom:none;margin-bottom:-2px;transition:all .2s}',
'.tab.active{color:#1a3a5c;background:#fff;border-color:#c5d5e8;border-bottom-color:#fff}',
'.tab:hover:not(.active){color:#1a3a5c;background:#e8f0fa}',
'.tab-pane{display:none;background:#fff;border-radius:0 12px 12px 12px;box-shadow:0 2px 8px rgba(0,0,0,.07);padding:24px;border:2px solid #c5d5e8}',
'.tab-pane.active{display:block}',
'.pane-title{font-size:15px;font-weight:700;color:#1a3a5c;margin-bottom:3px}',
'.pane-sub{font-size:11px;color:#9aacbe;margin-bottom:18px}',
'.grid2{display:grid;grid-template-columns:1fr 1fr;gap:18px}',
'@media(max-width:760px){.grid2{grid-template-columns:1fr}}',
'.chart-box{background:#f8fafc;border-radius:10px;padding:16px;position:relative}',
'.chart-box h4{font-size:13px;font-weight:600;color:#1a3a5c;margin-bottom:12px}',
'.chart-area{position:relative;height:360px}',
'.chart-area-tall{position:relative;height:430px}',
'.chart-area canvas{position:absolute;inset:0;width:100%!important;height:100%!important}',
'.chart-area-tall canvas{position:absolute;inset:0;width:100%!important;height:100%!important}',
'.msg{display:none;position:absolute;inset:0;flex-direction:column;align-items:center;justify-content:center;gap:10px;background:#f8fafc;border-radius:8px;z-index:5}',
'.msg.show{display:flex}',
'.msg-icon{font-size:38px}',
'.msg-text{font-size:13px;color:#aaa}',
'.district-badge{display:inline-flex;align-items:center;gap:6px;background:#e8f0fa;color:#1a3a5c;border-radius:20px;padding:4px 14px;font-size:12px;font-weight:700;margin-bottom:14px}',
'</style>',
'</head>',
'<body>',

'<div class="header">',
'  <div class="header-logo">&#127981;</div>',
'  <div class="header-text">',
'    <h1>Punjab Economic Census &mdash; Establishments Dashboard</h1>',
'    <p>District-level data: PSIC sectors, unit types &amp; employment size across Punjab</p>',
'  </div>',
'</div>',

'<div class="filters">',
'  <div class="filter-group">',
'    <label>Division</label>',
'    <select id="sel-div" onchange="onDivChange()"><option value="">All Divisions</option></select>',
'  </div>',
'  <div class="filter-group">',
'    <label>District</label>',
'    <select id="sel-dist" onchange="onDistChange()"><option value="">Select District</option></select>',
'  </div>',
'  <button class="btn-reset" onclick="resetAll()">&#x21ba; Reset</button>',
'</div>',

'<div class="content">',
'  <div id="summary"></div>',
'  <div>',
'    <div class="tabs">',
'      <div class="tab active" onclick="showTab(0)">&#128200; PSIC Sectors</div>',
'      <div class="tab" onclick="showTab(1)">&#127970; Unit Types</div>',
'      <div class="tab" onclick="showTab(2)">&#128101; Employment Size</div>',
'      <div class="tab" onclick="showTab(3)">&#9989; Unit &times; Employment</div>',
'    </div>',

'    <div class="tab-pane active" id="pane0">',
'      <div class="pane-title">PSIC Sector-wise Establishments &amp; Workforce</div>',
'      <div class="pane-sub">Table 1 &mdash; Number of establishments and workforce by major economic sector (PSIC classification).</div>',
'      <div class="grid2">',
'        <div class="chart-box">',
'          <h4>Establishments by Sector</h4>',
'          <div class="chart-area" id="wrap-pe">',
'            <canvas id="c-pe"></canvas>',
'            <div class="msg show" id="msg-pe"><div class="msg-icon">&#128270;</div><div class="msg-text">Select a district to view</div></div>',
'          </div>',
'        </div>',
'        <div class="chart-box">',
'          <h4>Workforce by Sector</h4>',
'          <div class="chart-area" id="wrap-pw">',
'            <canvas id="c-pw"></canvas>',
'            <div class="msg show" id="msg-pw"><div class="msg-icon">&#128101;</div><div class="msg-text">Select a district to view</div></div>',
'          </div>',
'        </div>',
'      </div>',
'    </div>',

'    <div class="tab-pane" id="pane1">',
'      <div class="pane-title">Unit Type-wise Establishments &amp; Workforce</div>',
'      <div class="pane-sub">Table 2 &mdash; Establishments and workforce distributed by business unit type.</div>',
'      <div class="grid2">',
'        <div class="chart-box">',
'          <h4>Establishments by Unit Type</h4>',
'          <div class="chart-area" id="wrap-ue">',
'            <canvas id="c-ue"></canvas>',
'            <div class="msg show" id="msg-ue"><div class="msg-icon">&#128270;</div><div class="msg-text">Select a district to view</div></div>',
'          </div>',
'        </div>',
'        <div class="chart-box">',
'          <h4>Workforce by Unit Type</h4>',
'          <div class="chart-area" id="wrap-uw">',
'            <canvas id="c-uw"></canvas>',
'            <div class="msg show" id="msg-uw"><div class="msg-icon">&#128101;</div><div class="msg-text">Select a district to view</div></div>',
'          </div>',
'        </div>',
'      </div>',
'    </div>',

'    <div class="tab-pane" id="pane2">',
'      <div class="pane-title">Employment Category by PSIC Sector</div>',
'      <div class="pane-sub">Table 3 &mdash; Establishments by sector and employment size (&lt;10 vs 10+ employees).</div>',
'      <div class="chart-box">',
'        <div class="chart-area-tall" id="wrap-ec">',
'          <canvas id="c-ec"></canvas>',
'          <div class="msg show" id="msg-ec"><div class="msg-icon">&#128270;</div><div class="msg-text">Select a district to view</div></div>',
'        </div>',
'      </div>',
'    </div>',

'    <div class="tab-pane" id="pane3">',
'      <div class="pane-title">Unit Type by Employment Category</div>',
'      <div class="pane-sub">Table 4 &mdash; Establishments by unit type and employment size (&lt;10 vs 10+ employees).</div>',
'      <div class="chart-box">',
'        <div class="chart-area-tall" id="wrap-ute">',
'          <canvas id="c-ute"></canvas>',
'          <div class="msg show" id="msg-ute"><div class="msg-icon">&#128270;</div><div class="msg-text">Select a district to view</div></div>',
'        </div>',
'      </div>',
'    </div>',

'  </div>',
'</div>',

'<script>',
paste0('const D=', json_str, ';'),

'const PAL=["#1a6eb5","#0e9e6b","#e07b00","#b81a1a","#6b3fa0","#0e7eb5","#9e1a6b","#3fa06b","#c0a000","#1a3a5c","#5dade2","#52be80","#f39c12","#e74c3c","#9b59b6","#1abc9c","#e67e22","#3498db","#2ecc71","#e91e63"];',
'let CH={};',

'// Label shortener',
'const SL={"Agriculture, forestry and fishing":"Agriculture","Mining and quarrying":"Mining","Manufacturing":"Manufacturing","Electricity, gas, steam and air conditioning supply":"Electricity/Gas","Water supply; sewerage, waste management and remediation activities":"Water/Waste","Construction":"Construction","Wholesale and retail trade; repair of motor vehicles and motorcycles":"Wholesale/Retail","Transportation and storage":"Transport","Accommodation and food service activities":"Food Service","Information and communication":"ICT","Financial and insurance activities":"Finance","Real estate activities":"Real Estate","Professional, scientific and technical activities":"Professional","Administrative and support service activities":"Admin Support","Public administration and defence; compulsory social security":"Public Admin","Education":"Education","Human health and social work activities":"Health","Arts, entertainment and recreation":"Arts/Rec","Other service activities":"Other Services","Activities of extraterritorial organizations and bodies":"Extraterritorial","Others":"Others"};',
'function sl(s){return SL[s]||(s.length>22?s.substr(0,20)+"...":s);}',
'function fmt(n){var v=Number(n);return isNaN(v)?"N/A":v.toLocaleString();}',
'function fk(n){var v=Number(n);if(!v)return"0";if(v>=1e6)return(v/1e6).toFixed(1)+"M";if(v>=1e3)return(v/1e3).toFixed(1)+"K";return v;}',
'function ttl(s){return s.split(" ").map(function(w){return w.charAt(0)+w.slice(1).toLowerCase();}).join(" ");}',

'// Show/hide overlay message — id matches suffix: pe, pw, ue, uw, ec, ute',
'function showMsg(id,yes){var el=document.getElementById("msg-"+id);if(el)el.classList.toggle("show",yes);}',

'// Destroy chart safely',
'function dc(id){if(CH[id]){CH[id].destroy();delete CH[id];}}',

'// Make bar chart — key: id is the suffix (pe, pw, ue, etc.), canvasId is "c-"+id',
'function mkBar(suffix,labels,datasets){',
'  dc(suffix);',
'  showMsg(suffix,false);',
'  var canvas=document.getElementById("c-"+suffix);',
'  if(!canvas){console.warn("No canvas for",suffix);return;}',
'  CH[suffix]=new Chart(canvas,{',
'    type:"bar",',
'    data:{labels:labels,datasets:datasets},',
'    options:{',
'      responsive:true,',
'      maintainAspectRatio:false,',
'      plugins:{',
'        legend:{position:"top",labels:{boxWidth:10,font:{size:10}}},',
'        tooltip:{callbacks:{label:function(c){return" "+c.dataset.label+": "+fmt(c.parsed.y);}}}',
'      },',
'      scales:{',
'        x:{ticks:{font:{size:9},maxRotation:45,minRotation:20},grid:{display:false}},',
'        y:{ticks:{font:{size:9},callback:function(v){return fk(v);}},beginAtZero:true,grid:{color:"#f0f4f8"}}',
'      }',
'    }',
'  });',
'}',

'// Get data rows for a table+district, filtering out Total rows',
'function getRows(tbl,dist){',
'  if(!dist)return[];',
'  var tblData=D[tbl];',
'  if(!tblData)return[];',
'  var r=tblData[dist];',
'  if(!r)return[];',
'  var arr=Array.isArray(r)?r:Object.values(r);',
'  return arr.filter(function(x){return x&&x.description&&x.description!=="Total";});',
'}',

'// Populate Division dropdown',
'var sdiv=document.getElementById("sel-div");',
'var sdist=document.getElementById("sel-dist");',
'Object.keys(D.divisions).forEach(function(d){',
'  var o=document.createElement("option");o.value=d;o.textContent=d;sdiv.appendChild(o);',
'});',

'function onDivChange(){',
'  var div=sdiv.value;',
'  sdist.innerHTML="<option value=\\"\\">Select District</option>";',
'  var dists=div?D.divisions[div]:Object.keys(D.psic).sort();',
'  dists.forEach(function(d){',
'    var o=document.createElement("option");o.value=d;o.textContent=ttl(d);sdist.appendChild(o);',
'  });',
'  render();',
'}',

'function onDistChange(){render();}',

'function resetAll(){sdiv.value="";onDivChange();}',

'function showTab(i){',
'  document.querySelectorAll(".tab").forEach(function(t,j){t.classList.toggle("active",i===j);});',
'  document.querySelectorAll(".tab-pane").forEach(function(t,j){t.classList.toggle("active",i===j);});',
'}',

'var ALL_SUFFIXES=["pe","pw","ue","uw","ec","ute"];',

'function render(){',
'  var dist=sdist.value||null;',

'  // --- Summary cards ---',
'  var pr=getRows("psic",dist);',
'  var er=getRows("employment",dist);',
'  var ur=getRows("unit_type",dist);',
'  var te=0,tw=0,tl=0,tg=0;',
'  pr.forEach(function(r){te+=Number(r.establishments)||0;tw+=Number(r.workforce)||0;});',
'  er.forEach(function(r){tl+=Number(r.less_than_10)||0;tg+=Number(r.ten_and_above)||0;});',
'  var badge=dist?"<div class=\\"district-badge\\">&#128205; "+ttl(dist)+"</div>":"";',
'  document.getElementById("summary").innerHTML=badge+',
'  "<div class=\\"summary-row\\">"+',
'  "<div class=\\"card\\"><div class=\\"card-label\\">Total Establishments</div><div class=\\"card-value\\">"+fmt(te)+"</div><div class=\\"card-sub\\">All sectors combined</div></div>"+',
'  "<div class=\\"card green\\"><div class=\\"card-label\\">Total Workforce</div><div class=\\"card-value\\">"+fmt(tw)+"</div><div class=\\"card-sub\\">Persons employed</div></div>"+',
'  "<div class=\\"card amber\\"><div class=\\"card-label\\">Small (&lt;10 Empl.)</div><div class=\\"card-value\\">"+fmt(tl)+"</div><div class=\\"card-sub\\">Micro establishments</div></div>"+',
'  "<div class=\\"card red\\"><div class=\\"card-label\\">Large (10+ Empl.)</div><div class=\\"card-value\\">"+fmt(tg)+"</div><div class=\\"card-sub\\">Larger establishments</div></div>"+',
'  "<div class=\\"card purple\\"><div class=\\"card-label\\">Active Sectors</div><div class=\\"card-value\\">"+pr.filter(function(r){return Number(r.establishments)>0;}).length+"</div><div class=\\"card-sub\\">PSIC categories</div></div>"+',
'  "<div class=\\"card\\"><div class=\\"card-label\\">Unit Types</div><div class=\\"card-value\\">"+ur.length+"</div><div class=\\"card-sub\\">Distinct categories</div></div>"+',
'  "</div>";',

'  // If no district — destroy charts and show messages',
'  if(!dist){',
'    ALL_SUFFIXES.forEach(function(s){dc(s);showMsg(s,true);});',
'    return;',
'  }',

'  // --- Tab 1: PSIC Establishments & Workforce ---',
'  var pf=pr.filter(function(r){return Number(r.establishments)>0||Number(r.workforce)>0;});',
'  var pl=pf.map(function(r){return sl(r.description);});',
'  var pc=pf.map(function(_,i){return PAL[i%PAL.length];});',
'  if(pf.length){',
'    mkBar("pe",pl,[{label:"Establishments",data:pf.map(function(r){return Number(r.establishments)||0;}),backgroundColor:pc,borderRadius:4}]);',
'    mkBar("pw",pl,[{label:"Workforce",data:pf.map(function(r){return Number(r.workforce)||0;}),backgroundColor:pc.map(function(c){return c+"99";}),borderRadius:4}]);',
'  } else {dc("pe");showMsg("pe",true);dc("pw");showMsg("pw",true);}',

'  // --- Tab 2: Unit Type ---',
'  var uf=ur.filter(function(r){return Number(r.establishments)>0;});',
'  var ul=uf.map(function(r){return r.description;});',
'  var uc=uf.map(function(_,i){return PAL[i%PAL.length];});',
'  if(uf.length){',
'    mkBar("ue",ul,[{label:"Establishments",data:uf.map(function(r){return Number(r.establishments)||0;}),backgroundColor:uc,borderRadius:4}]);',
'    mkBar("uw",ul,[{label:"Workforce",data:uf.map(function(r){return Number(r.workforce)||0;}),backgroundColor:uc.map(function(c){return c+"99";}),borderRadius:4}]);',
'  } else {dc("ue");showMsg("ue",true);dc("uw");showMsg("uw",true);}',

'  // --- Tab 3: Employment Category ---',
'  var ef=er.filter(function(r){return Number(r.less_than_10)>0||Number(r.ten_and_above)>0;});',
'  if(ef.length){',
'    mkBar("ec",ef.map(function(r){return sl(r.description);}),[',
'      {label:"< 10 Employees",data:ef.map(function(r){return Number(r.less_than_10)||0;}),backgroundColor:"#1a6eb5",borderRadius:4},',
'      {label:"10+ Employees",data:ef.map(function(r){return Number(r.ten_and_above)||0;}),backgroundColor:"#0e9e6b",borderRadius:4}',
'    ]);',
'  } else {dc("ec");showMsg("ec",true);}',

'  // --- Tab 4: Unit Type x Employment ---',
'  var uer=getRows("unit_employment",dist);',
'  var uef=uer.filter(function(r){return Number(r.less_than_10)>0||Number(r.ten_and_above)>0;});',
'  if(uef.length){',
'    mkBar("ute",uef.map(function(r){return r.description;}),[',
'      {label:"< 10 Employees",data:uef.map(function(r){return Number(r.less_than_10)||0;}),backgroundColor:"#1a6eb5",borderRadius:4},',
'      {label:"10+ Employees",data:uef.map(function(r){return Number(r.ten_and_above)||0;}),backgroundColor:"#0e9e6b",borderRadius:4}',
'    ]);',
'  } else {dc("ute");showMsg("ute",true);}',
'}',

'// Init',
'onDivChange();',
'</script>',
'</body>',
'</html>'
)

writeLines(lines, 'EC_Census_Dashboard.html', useBytes=TRUE)
cat('Dashboard rebuilt OK\n')
cat('File size KB:', round(file.size('EC_Census_Dashboard.html')/1024, 1), '\n')
